### ISSUE TITLE
Psycopg2 in requirements

### ISSUE THREAD

**Issue by dihmandrake** [EN152/dcp#128]
Brauchen wir wirklich die Psycopg2? Wenn ja, wofür?
Habe beim install immer einen Fehler

**Comment by eliasgruenewald** [comment]
Psycopg2 is a DB API 2.0 compliant PostgreSQL driver

...und bei mir gibt es auch immer nur fehler. ich denke auch, dass das erstmal rauskann. ob wir jemals noch auf postgres umziehen ist derzeit ja auch noch nicht so ganz klar :D

**Comment by dihmandrake** [comment]
Okay. Werde es demnächst auskommentieren. Falls irgendwer dann Fehler hat nehmt es einfach wieder rein

**Comment by dihmandrake** [comment]
Ohne das Modul failen die Travis builds. Ist wieder einkommentiert..
