### ISSUE TITLE
Als Benutzer möchte ich ein nicht vorhandenes oder nicht zufriedenstellendes Gebot melden können.

### ISSUE THREAD

**Issue by n1ck3l222** [EN152/dcp#36]

**Comment by dihmandrake** [comment]
Ist doch schon implementiert

**Comment by dihmandrake** [comment]
Man hat halt keinen Melden Button, wenn man das Good selber erstellt hat

**Comment by eliasgruenewald** [comment]
Na klar, hab ich doch eben sogar in der Präsi gesagt :D
aber niemand verwaltet die meldungen.
als admin möchte ich eine liste von posts, die mehr als 2 (3, 4, 5...) meldungen haben und kann diese dann löschen

**Comment by dihmandrake** [comment]
Wäre das nicht einfach eine Filter Funktion?
Melden >= x oder Melden + x >= Bump

**Comment by dihmandrake** [comment]
Also soll ich jetzt einfach einen Highlighter bzw. extra Seite dafür schreiben oder machen wir das als Filter?

**Comment by eliasgruenewald** [comment]
Extra "Überblick gemeldeter Beiträge"-Seite finde ich die beste Lösung.
Freiwillige vor! :)
